import type { Product } from "./types";

export const sampleProducts: Product[] = [
  {
    id: "prd-cafe-001",
    sku: "CAF-001",
    name: "Cafe premium 500g",
    category: "Alimentos",
    brand: "Demo",
    motor: "",
    crossRef: "",
    customerRef: "",
    location: "A1-1",
    initialStock: 42,
    entries: 0,
    exits: 0,
    stock: 42,
    minStock: 15,
    unitCost: 18500,
    price: 28900,
    supplier: "Distribuidora Norte",
    updatedAt: new Date().toISOString(),
    source: "demo"
  },
  {
    id: "prd-jabon-001",
    sku: "LIM-014",
    name: "Jabon liquido 1L",
    category: "Limpieza",
    brand: "Demo",
    motor: "",
    crossRef: "",
    customerRef: "",
    location: "A1-2",
    initialStock: 9,
    entries: 0,
    exits: 0,
    stock: 9,
    minStock: 12,
    unitCost: 7200,
    price: 11900,
    supplier: "Quimicos Andinos",
    updatedAt: new Date().toISOString(),
    source: "demo"
  },
  {
    id: "prd-cable-001",
    sku: "TEC-112",
    name: "Cable USB-C 1m",
    category: "Tecnologia",
    brand: "Demo",
    motor: "",
    crossRef: "",
    customerRef: "",
    location: "B2-1",
    initialStock: 68,
    entries: 0,
    exits: 0,
    stock: 68,
    minStock: 20,
    unitCost: 6400,
    price: 14900,
    supplier: "Importadora Delta",
    updatedAt: new Date().toISOString(),
    source: "demo"
  }
];
